spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/cricketdb?createDatabaseIfNotExists=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dorc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #database-platform: org.hibernate.dialect.Dialect] # Change to MySQL5InnoDBDialect if using MySQL 5.7 or older
    hibernate:
      ddl-auto: update
    show-sql: true  # Logs SQL queries in console
    properties:
      hibernate:
        format_sql: true  # Pretty print SQL logs
  application:
    name: cricket-app


